language: java
jdk:
  - openjdk-ea
  - openjdk17
  - openjdk11
  - openjdk8

env:
  global:
    - STOREPASS=password

matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk-ea

after_success:
  - mvn clean test jacoco:report-aggregate coveralls:report -DjacocoReports=jsign/target/site/jacoco-aggregate/jacoco.xml

cache:
  directories:
  - $HOME/.m2
