language: java
jdk:
  - openjdk-ea
  - openjdk17
  - openjdk11
  - openjdk8

matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk-ea
    - jdk: openjdk17

after_success:
  - mvn clean test jacoco:report-aggregate coveralls:report

cache:
  directories:
  - $HOME/.m2
